---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "foundation-delegation.fullname" . }}-backend
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app: {{ template "foundation-delegation.fullname" . }}-backend
  ports:
  - name: delegation-backend
    port: {{ .Values.backend.port }}
    targetPort: backend
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "foundation-delegation.fullname" . }}-ingress
spec:
  tls:
  - secretName: {{ .Values.backend.tlsSecret }}
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "foundation-delegation.fullname" . }}-backend
            port:
              number: {{ .Values.backend.port }}
