steps:
  - command: echo "Hello! This is the new pipeline"
    label: "Example Test"
  - command: "example.sh"
    label: "Shell script test"
  - command: "example.py"
    label: "Python script test"
  
