steps:
  - command: echo "Hello! This is the new pipeline"
    label: "Example Test"
  - command: "buildkite/pipelines/example.sh"
    label: "Shell script test"
  - command: "python3 ./buildkite/pipelines/example.py"
    label: "Python script test"
  
