{{ range $node := $.Values.nodes }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.deployment.name }}-{{ $node.name }}
  labels:
    app: {{ $.Values.deployment.name }}-{{ $node.name }}
spec:
  replicas: {{ $node.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.deployment.name }}-{{ $node.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.deployment.name }}-{{ $node.name }}
        testnet: {{ $.Values.deployment.testnet }}
        role: {{ default "undefined" $node.role }}
        class: {{ default "undefined" $node.class }}
        version: {{ trunc 8 (split ":" $.Values.deployment.image)._1 | trimSuffix "-" }}
        syncStatus: INIT
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ $node.ports.metrics | quote }}
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      {{ if $node.libp2pKeys.enabled -}}
      - name: fix-libp2p-perms
        image: busybox:latest
        command:
        - bash
        - -c
        - /bin/cp /libp2p-keys/* /root/libp2p-keys && /bin/chmod -R 0700 /root/libp2p-keys/
        volumeMounts:
        - name: mounted-libp2p-keys
          mountPath: /libp2p-keys
        - name: fixed-libp2p-keys
          mountPath: /root/libp2p-keys
      {{- end }}
      {{ if $node.minaKeys.enabled -}}
      - name: fix-mina-perms
        image: busybox:latest
        command:
        - bash
        - -c
        - /bin/cp /mina-keys/* /root/mina-keys/ && /bin/chmod -R 0700 /root/mina-keys/
        volumeMounts:
        - name: mounted-mina-keys
          mountPath: /mina-keys
        - name: fixed-mina-keys
          mountPath: /root/mina-keys
      {{- end }}
      containers:
      - name: mina
        resources:
          limits:
          requests:
            memory: {{ $.Values.requests.memory }}
            cpu: {{ $.Values.requests.cpu }}
        image: {{ $.Values.deployment.image }}
        {{ if $.Values.deployment.customEntrypoint.enabled -}}
        command: [{{ $.Values.deployment.customEntrypoint.entrypoint }}]
        {{- end }}
        args: [ "daemon",
          {{- if $node.fileLogLevel }}
          "--file-log-level", {{ $node.fileLogLevel | quote }},
          {{- end -}}
          {{- if $node.logLevel }}
          "--log-level", {{ $node.logLevel | quote }},
          {{- end -}}
          "--client-port", "$(DAEMON_CLIENT_PORT)",
          "--rest-port", "$(DAEMON_REST_PORT)",
          "--external-port", "$(DAEMON_EXTERNAL_PORT)",
          "--metrics-port", "$(DAEMON_METRICS_PORT)",
          {{- if $node.exposeGraphql }}
          "--insecure-rest-server",
          {{- end -}}
          {{- if $node.maxConnections }}
          "--max-connections", {{ $node.maxConnections | quote }},
          {{- end -}}
          {{- if $.Values.deployment.peerListURL }}
          "--peer-list-url", {{ $.Values.deployment.peerListURL | quote }},
          {{- end -}}
          {{- if $.Values.deployment.runtimeConfig }}
          "--config-file", "/config/daemon.json",
          {{- end }}
          {{- if $node.libp2pKeys.enabled }}
          "--discovery-keypair", "/root/libp2p-keys/{{ $node.name }}-libp2p",
          {{- end -}}
          {{- if and $node.minaKeys.enabled $node.minaKeys.produceBlocks }}
          "--block-producer-key", "/root/mina-keys/{{ $node.name }}-key",
          {{- end -}}
          {{- range $.Values.deployment.seedPeers }}
          "--peer", {{ . | quote }},
          {{- end }}
          {{- if $.Values.deployment.uploadBlocksToGCloud }}
          "-upload-blocks-to-gcloud", "true",
          {{- end }}
          {{- if $node.archive.enabled }}
          "-archive-address", {{ $node.archive.address }},
          {{- end }}
          {{- if $node.seedFlags }}
          "-enable-peer-exchange", "true", "-seed",
          {{- end}}
          "--log-json"
        ]
        env:
        - name: NETWORK_NAME
          value: {{ $.Values.deployment.testnet }}
        - name: DAEMON_REST_PORT
          value: {{ $node.ports.graphql | quote }}
        - name: DAEMON_CLIENT_PORT
          value: {{ $node.ports.client | quote }}
        - name: DAEMON_METRICS_PORT
          value: {{ $node.ports.metrics | quote }}
        - name: MINA_CLIENT_TRUSTLIST
          value: "10.0.0.0/8"
        {{- if $.Values.deployment.uploadBlocksToGCloud }}
        - name: GCLOUD_KEYFILE
          value: "/gcloud/keyfile.json"
        - name: GCLOUD_BLOCK_UPLOAD_BUCKET
          value: "mina_network_block_data"
        {{- end }}
        - name: DAEMON_EXTERNAL_PORT
          value: {{ $node.ports.p2p | quote }}
        {{- if $node.libp2pKeys.enabled }}
        - name: MINA_LIBP2P_PASS
          valueFrom:
            secretKeyRef:
              name: {{ $node.name }}
              key: "libp2p-password"
        {{- end }}
        {{- if $node.minaKeys.enabled }}
        - name: MINA_PRIVKEY_PASS
          valueFrom:
            secretKeyRef:
              name: {{ $node.name }}
              key: "key-password"
        {{- end }}
        ports:
        - name: client-port
          protocol: TCP
          containerPort: {{ $node.ports.client }}
        - name: graphql-port
          protocol: TCP
          containerPort: {{ $node.ports.graphql }}
        - name: metrics-port
          protocol: TCP
          containerPort: {{ $node.ports.metrics }}
        - name: external-port
          protocol: TCP
          containerPort: {{ $node.ports.p2p }}
          hostPort: {{ $node.ports.external }}
{{$data := dict "name" $node.name "healthcheck" $.Values.healthcheck }}
{{- include "healthcheck.seed.allChecks" $data | indent 8 }}
        imagePullPolicy: Always
        volumeMounts:
        {{- if $node.libp2pKeys.enabled }}
        - name: actual-libp2p
          mountPath: /root/libp2p-keys
        {{- end }}
        {{- if $.Values.deployment.uploadBlocksToGCloud }}
        - name: gcloud-keyfile
          mountPath: "/gcloud/"
        {{- end }}
        {{- if $.Values.deployment.runtimeConfig }}
        - name: daemon-config
          mountPath: "/config/"
        {{- end }}
      volumes:
      {{- if $.Values.deployment.runtimeConfig }}
      - name: daemon-config
        configMap:
          name: daemon-config
      {{- end }}
      {{- if $node.minaKeys.enabled }}
      - name: mounted-mina-keys
        secret:
          secretName: {{ $node.name }}
          defaultMode: 0600
          items:
          - key: {{ $node.name }}-key
            path: {{ $node.name }}-key
          - key: {{ $node.name }}-key.pub
            path: {{ $node.name }}-key.pub
      - name: fixed-mina-keys
        emptyDir: {}
      {{- end }}
      {{- if $node.libp2pKeys.enabled }}
      - name: mounted-libp2p-keys
        secret:
          secretName: {{ $node.name }}
          defaultMode: 0600
          items:
          - key: {{ $node.name }}-libp2p
            path: {{ $node.name }}-libp2p
          - key: {{ $node.name }}-libp2p.peerid
            path: {{ $node.name }}-libp2p.peerid
      - name: fixed-libp2p-keys
        emptyDir: {}
      {{- end }}
      {{- if $node.uploadBlocksToGCloud }}
      - name: gcloud-keyfile
        secret:
          secretName: gcloud-keyfile
          defaultMode: 0400
          items:
          - key: keyfile
            path: keyfile.json
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.deployment.name }}-{{ $node.name }}
spec:
  {{- if $node.ip }}
  type: LoadBalancer
  loadBalancerIP: {{ $node.ip }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  # We want all pods to have their addresses published for the sake of the
  # other testnet pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  selector:
    app: {{ $.Values.deployment.name }}-{{ $node.name }}
  ports:
  - name: tcp-p2p
    port: {{ $node.ports.p2p }}
    targetPort: external-port
---
{{- if $node.exposeGraphql }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.deployment.name }}-{{ $node.name }}-graphql
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: {{ $.Values.deployment.name }}-{{ $node.name }}
  ports:
  - name: http-graphql
    protocol: TCP
    port: 80
    targetPort: {{ $node.ports.graphql }}
{{- end }}
---
{{- end }}
