queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
    #   - check-success=ci-one
    #   - check-success=ci-two

pull_request_rules:
    - name: automatically merge approved PRs with the ready-to-merge label
      conditions:
          - "status-success=buildkite/mina-pr-gating"
          - "status-success=buildkite/mina/pr"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge
      actions:
          queue:
              method: merge
              strict: default
          delete_head_branch: {}
    - name: automatically merge approved PRs into develop with the ready-to-merge-into-develop label
      conditions:
          - "status-success=buildkite/mina-pr-gating"
          - "status-success=buildkite/mina/pr"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge-into-develop
          - base=develop
      actions:
          queue:
              method: merge
              strict: default
          delete_head_branch: {}
    - name: automatically merge approved PRs into develop-until-4.1-hardfork with the ready-to-merge-into-develop label
      conditions:
          - "status-success=buildkite/mina-pr-gating"
          - "status-success=buildkite/mina/pr"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge-into-develop
          - base=develop-until-4.1-hardfork
      actions:
          queue:
              method: merge
              strict: default
          delete_head_branch: {}
    - name: automatically merge approved PRs into develop-until-adversarial with the ready-to-merge-into-develop label
      conditions:
          - "status-success=buildkite/mina-pr-gating"
          - "status-success=buildkite/mina/pr"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge-into-develop
          - base=develop-until-adversarial
      actions:
          queue:
              method: merge
              strict: default
          delete_head_branch: {}
