apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itn-services.fullname" . }}-log-fetcher
  labels:
    {{- include "itn-services.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-log-fetcher
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-log-fetcher
    spec:
      containers:
        - name: log-fetcher
          image: gcr.io/o1labs-192920/mina-internal-trace-consumer:1.2.0
          command:
            - bash
            - -c
            - fetcher -k /keys/secret_key -o /output -n /names-data/node_names.json --db-uri 'postgresql://<postgresuser>:<postgressecret>@postgres:5432' discovery
          env:
            - name: NETWORK
              value: "ITN"
            # - name: GOOGLE_BUCKET
            #   value: "uptime-itn-pre-launch-sanity-check"
            - name: GOOGLE_SERVICE_ACCOUNT
              value: "/credentials/itn-keyfile.json"
            - name: INTERNAL_TRACE_CONSUMER_EXE
              value: "/internal_trace_consumer"
            - name: AWS_DEFAULT_REGION
              value: "us-west-2"
            - name: AWS_BUCKET
              value: "673156464838-block-producers-uptime"
            - name: AWS_PREFIX
              value: "berkeley"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: unnamed-port
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: gcloud-keyfile
              mountPath: "/credentials/"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: gcloud-keyfile
          secret:
            secretName: gcloud-keyfile
            defaultMode: 256
            items:
              - key: keyfile
                path: itn-keyfile.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
