version: '3.3'
services:
  configuration:
    build: .
    network_mode: host
    command: ["/bin/sh", "scripts/archive/make_hasura_configurations.sh"]
    depends_on:
    - "hasura"
    volumes:
      - .:/home/opam/opam-repository/scripts/archive
      - ../introspection_query.py:/home/opam/opam-repository/scripts/introspection_query.py
      - ./output:/home/opam/opam-repository/output