version: '3.6'
services:
  postgres: 
    image: postgres:12
    environment: 
      POSTGRES_PASSWORD: codarules
      POSTGRES_USER: admin
      POSTGRES_DB: archiver
    volumes:
    - /var/lib/postgresql/data
    - ../../src/app/archive/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports: 
    - "5432:5432"
  hasura: 
    image: hasura/graphql-engine:v1.0.0-beta.6
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:codarules@postgres:5432/archiver
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    ports: 
    - "9000:8080"
    depends_on:
    - "postgres"
    restart: always
  configuration:
    image: codaprotocol/coda:toolchain-6b64dedbb6e27f0cc57228f1b44aaa87da489e83
    network_mode: host
    command: ["/bin/sh", "scripts/archive/make_hasura_configurations.sh"]
    depends_on:
    - "hasura"
    volumes:
      - .:/home/opam/opam-repository/scripts/archive
      - ../introspection_query.py:/home/opam/opam-repository/scripts/introspection_query.py
      - ./output:/home/opam/opam-repository/output

