---
name: "generic-node"

testnetName: "testnet"

image:
  repository: minaprotocol/mina-daemon
  pullPolicy: IfNotPresent
  tag: 1.2.1alpha1-1f98b8b-devnet

features:
  logsnarkworkgossip:
    enabled: true
  enablepeerexchange:
    enabled: true
  runtimeConfig:
    enabled: false
  maxConnections: 200
  logTxnPoolGossip:
    enabled: false
  exposeGraphql:
    enabled: false
  uploadBlocksToGCloud:   # Added this
    enabled: true
  customEntrypoint:
    enabled: false
    command: ""
  prometheus:
    enabled: true
  persistence:
    enabled: true
    name: "generic-node-volume"
    storageClass: standard-delete
    mountPath: /data/
    size: 100Gi
  privateKeySecret:
    enabled: true
    secretName: "generic-node-devnet-bp-key"
  daemon:
    args:
      - "--libp2p-metrics-port"
      - "9000"
      - "--log-txn-pool-gossip"
      - "true"
      - "--peer-list-url"
      - "https://storage.googleapis.com/seed-lists/{{.Values.testnetName}}_seeds.txt"
      - "--enable-peer-exchange"
      - "true"
  seedPeers: []

publicKey: "" #"4vsRCVadXwWMSGA9q81reJRX3BZ5ZKRtgZU7PtGsNq11w2V9tUNf4urZAGncZLUiP4SfWqur7AZsyhJKD41Ke7rJJ8yDibL41ePBeATLUnwNtMTojPDeiBfvTfgHzbAVFktD65vzxMNCvvAJ"
snarkFee: "0.025"
workSelectionAlgorithm: seq #seq OR rand

archive:
  enabled: true
  image:
    repository: minaprotocol/mina-archive
    pullPolicy: IfNotPresent
    tag: 1.2.1alpha1-1f98b8b-devnet
  pg_conn: 'postgres://postgresql:5432'

rosetta:
  enabled: false
  image:
    repository: minaprotocol/mina-rosetta-ubuntu
    pullPolicy: IfNotPresent
    tag: 1.3.0alpha2-compatible-513333d-stretch
  pg_conn: 'postgres://postgresql:5432'
  graphql_host: 'http://127.0.0.1'

libp2p:
  seed:
    enabled: true
  staticKeypair:
    enabled: true
    secretName: "generic-node-devnet-libp2p-key"
  loadBalancer:
    enabled: true

servicekey:
  secretName: "faucet-service-key"

ports:
  client: "8301"
  graphql: "3085"
  metrics: "10001"
  p2p: "10909"
  nodePort: "30004"
  postgres: "5432"
  archive: "3086"
  rosetta: "3087"

resources:
  limits:
  requests:
    memory: "32Gi"
    cpu: "12"
    rayonThreads: "6"

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 10
  initialDelaySeconds: 30
  seed:
    healthcheck.seed.allChecks:
  daemon:
    healthcheck.daemon.allChecks:

nodeSelector:
  preemptible: true
