---
name: "generic-node"

testnetName: "testnet"

image:
  repository: minaprotocol/mina-daemon
  pullPolicy: IfNotPresent
  tag: 1.2.1alpha1-1f98b8b-devnet

features:
  runtimeConfig:
    enabled: false
  maxConnections: 200
  logTxnPoolGossip:
    enabled: false
  exposeGraphql:
    enabled: false
  uploadBlocksToGCloud:   # Added this
    enabled: false
  customEntrypoint:
    enabled: false
    command: ""
  seedPeers: []

libp2p:
  seed:
    enabled: true
  staticKeypair:
    enabled: true
    secretName: "some-libp2p-key"
  loadBalancer:
    enabled: true

servicekey:
  secretName: "faucet-service-key"

privateKeySecret:
  secretName: "" 

ports:
  client: "8301"
  graphql: "3085"
  metrics: "10001"
  p2p: "10909"
  nodePort: "30005"
  postgres: "5432"

resources:
  limits:
  requests:
    memory: "32Gi"
    cpu: "12"
    rayonThreads: "6"

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 10
  initialDelaySeconds: 30
  seed:
    healthcheck.seed.allChecks:
  daemon:
    healthcheck.daemon.allChecks:

nodeSelector:
  preemptible: true
