apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "email-cron"
spec:
  schedule: "0 0 */15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: {{ .Values.cron.image }}
              imagePullPolicy: Always
              command:
                - /usr/local/bin/python
                - send_email.py
          restartPolicy: OnFailure
