apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "leaderboard.fullname" . }}-ui
  labels:
    app: {{ template "leaderboard.fullname" . }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "leaderboard.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ template "leaderboard.fullname" . }}-ui
        role: leaderboard
        version: {{ trunc 6 (split ":" .Values.ui.image)._1 | trimSuffix "-" }}
    spec:
      containers:
      - name: ui
        image: {{ .Values.ui.image }}
        imagePullPolicy: Always
        ports:
        - name: leaderboard-ui
          protocol: TCP
          containerPort: {{ .Values.ui.port }}
