# kubectl apply -f helm/staking-ledger-cron/mainnet-dump-staking-ledger-cronjob.yaml
# the above command, with this accompanying file, needs only be run once.  it does not get run in CI.  this file is provided here for future reference
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mainnet-dump-staking-ledger-cronjob
spec:
  # schedule: "0 11 * * *"
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mainnet-dump-staking-ledger-container
            image: codaprotocol/coda-daemon:1.1.5-mina-dockerfiles-entrypoints-91989f2
            # command: ["/usr/bin/dumb-init", '/cron_job_dump_ledger.sh']
            command: ["/usr/bin/dumb-init", 'mina daemon --generate-genesis-proof true --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt --background;sleep 480;while true;do mina ledger export staking-epoch-ledger>staking_epoch_ledger.txt;if [ "$?" -eq 0 ];then echo "ledger dumped!";cat staking_epoch_ledger.txt;break;else echo "waiting for staking ledger to become available, sleeping for 30s";sleep 30;fi;done;STAKING_LEDGER_HASH = mina ledger hash --ledger-file staking_epoch_ledger.txt;DATE = "$(date +%F_%H%M)";mv ./staking_epoch_ledger.txt ./$(DATE)_staking_epoch_ledger_$(staking_ledger_hash).txt;mina ledger export next-epoch-ledger>next_epoch_ledger.txt;NEXT_LEDGER_HASH = mina ledger hash --ledger-file next_epoch_ledger.txt;mv ./next_epoch_ledger.txt ./$(DATE)_next_epoch_ledger_$(next_ledger_hash).txt' ]
          restartPolicy: Never
