apiVersion: v1
data:
  key-password: alBIQzRWS053YzM0SE1na2NYeEtuVzlobWhDUmQ5TXd0WFdKSHN2dDNzN3BkZ0Zqcm5XZExKbk5rcTluY2NNdg==
  libp2p-password: VmtXejNrZ1hDbXBocGd2V05zS2hqOTlyM2hXZkx2YmRLNFZqaGdNdndWOU1mUE1ybWNna2N4eHpLNFJ6N3dXVw==
  seed-1-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6Ijd0dmNjUHlwQ3hjZW14OUtpUFo0b0tYM0h4eWJBZ25pSHhXZGhRRCIsInB3c2FsdCI6IjluZ0dpNEJWNDZ2NzRLQzNGYjFyUGd6dTdSb0EiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJESHkyTjVGTkNMaWJRcnFpUW1TRWlVUWJzaUVNY2pxQ3ZHN1ZMVWhmdXNzMlVkTGhZRUFGYm5yZkM3S0dMMnlZSGlER2NlQlIyIn0=
  seed-1-key.pub: QjYycWtLb0JBWEh1UXpBV2VDRWlpdkN1YkszYnZ2ZUFlaWNqYWNCdkNZd2V0cHJLSmlZQlRCNAo=
  seed-1-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjdxZktmc20xUGJ1RjVobTltakR6NkRGSDNhTVJlNHV1ZWtDNlNyUiIsInB3c2FsdCI6IjlpcHJZTnBtOWpIWks2NVRac3pkODM5Nm5Ya1YiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI4akVyNDdlTjFuZGRpblB6QzFOamRTTlcyaEVtMjVGenNDa0tnTjg3dDh4TFNLVEh1aTc4eXFSRllIVm1RQmlOaWc2SnNjczRFbmNNNlFHMmptcHcxNkZ1a1Zkbmk4QXlxb2I3U1JDRUhUWnFScWkxOFg3Vm9aZ2hyZGRuSkxwUUU1YmdCb0pOZkZDbTkyS0xiQlhha3JXV2pqSHpaM3l2RTVTb2RXQ3Z2YW5YazRQanVOV3VheHlnVlMyODVnOWZORUhXWjZBd3FCODRWYno5ZHRxRFVoOVFjQXBFYzhxWFRkNmNXelN2OUNEYUFFMXBnRWF0QVJlNFNlcVVhanh3WEpxM2VMNjFxYjRGa0FIUXhTUlVkUlE0dkxNRVhCd2F5eHBSaCJ9
  seed-1-libp2p.peerid: MTJEM0tvb1dGRFlQdnNyMmRhSlpXVDJZNzZkMkoxN3Z1dlFTdlI5SGFaWkZWSmFuZnVScQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-1
---
apiVersion: v1
data:
  key-password: dk1oWGtzZG1uTkpMend0aHhqTmhMTE5wcTRuVHhOd3I5Snp3eGdMUmZmRjltQ0tUY1J4UHJtakx2TXpuY2dUeg==
  libp2p-password: TFh2dFZKYkY3WGZrM2R0M3MzUDloVGpxZFdWOWpWc256Y01nbnRnZnpuSnd0cldySnpGMzNGc25XNzdQZG5yWA==
  seed-2-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhQTEU1WVdZVkNrZ280M0JQb21RU2E2Y1JCTnY2YUFEVGh1cGlRbiIsInB3c2FsdCI6IkFzaWd3WWRvZDllZnEyb0NEOWZIQUhYdG8yUGsiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJDN3JOZEZ2SFZodkJ1OENzYjRNTnpxQjY1QmhpcmRqUzF1aVpScGlZbzN4WGhTNXg1SHNQQkh2eFdIV3BRR3A3ZmJqUlRGcTl6In0=
  seed-2-key.pub: QjYycW5KcFRTMzZyaG51MjJ6bmdHcUdNN1BCc1U3V3R0NmI5dXI1RUFWQlpVdFJGZEhHU2dIOAo=
  seed-2-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjZVcmkzSmE4SmJnekJjZkhnRmREZFdXcU0zbkJmR01QVTFESzJLeCIsInB3c2FsdCI6IjhWV2tZMjM0R2dhYVpHYVc4NG1ZdmN5WnA0UU4iLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI4YmU5YjJFNEJ3WXpGc3h4VjNLM0VDUTRXdjR5bUx0QkhERWl4V1RnajVMemo3WkRCbzRURWk5NkpuczN5RzZXVTk1U0Q5dHZuWUJvM1M1MnlhWUt6WWhuVHJQOFVKQkNzem9INUVzTWhhclc1UzdGZXdMUW1GRVBmM2hGWWJLaEZmbjhqM2ptaHdiUzE1Q2p1WW96ZTM4VERlb3l2NE5BcHVzUkRmcWhGSFJiclg2c2F6OW5ocmlHQmdMVkY5bnlETDM2RWd1RHJFN0ttY0dVU3RkRVBQalFLbUt5aWN0cjNlOU53R1ZpUm5CYTd6OEJ1dUNxRHZWbmhqWkd0TVEzSmdnV3N1WDNpUlp5WW53UndnUWNHVUhIajQ4dnVkd0FaMUdUYiJ9
  seed-2-libp2p.peerid: MTJEM0tvb1dGZ1NkQVpxOUF6UXpSR3pWTEVNWk1TVW9VYVBkYTM2OGp5anJYRzV0akpKTgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-2
---
apiVersion: v1
data:
  key-password: bnBMVExXTWttWGJ2ck1SOVR0ZHhjeHNiczRoRkpQVE5MY3pzTHdqaDl3S1A5cXBDRjNnZEpOOWZxd2NoUGY5Mw==
  libp2p-password: VGhzemJkTFA0ZmJnczlIRjNUN2M5a25iOXp4cUpQSGpkcnNMc2hLSndrbW5jVFB3Y0g5Vjl2eGNoVktObkt2eg==
  seed-3-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjZibTJqZXZaMlFGSnAzTG1ZRGhpYndSWHgxY3hZeWc2TUh6UHdYaiIsInB3c2FsdCI6IjltQ0J6eGoydEE3cncxZ29KRW5hRXRYMmt2YzciLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJFSmpaeTM4UmY2Rk1SZnNaOURidDFrS3pIQ2ZkeDZZRlM1Z2FtSGphMW91Wm5HcW96d1lxRlhjRmJlSlJ5SjZDelZBNVI5RXVEIn0=
  seed-3-key.pub: QjYycXI2aXpOSExKb2hBdGZLbXBSTDFWQ1BSeHRjVGZVZmtyWEVwYldlUmhhQ1p1TXZGUWM1Ygo=
  seed-3-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhmS29hbndkcmNRNzFEeVl1Q2lGcDlQbWlCOEdiNHlZWHo2U24xciIsInB3c2FsdCI6IkE1Z3dlSkhqenl3aHFORHlEeVk1RVNGTFNnSFMiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI4WXJMQ1JpYXBqbnJyUUxiblBGWlZiZ1hjdjhRdVdpZHhaQ1l2dU5aNlM3YW1hQzdVQXFpS2txR1U3WXA5VHJwcGhSaDdHaVlzOW5zcjI1WmVIelNwMUJ2QnpVeVhkUTFnejQxVkJBcmIzdUtwYjh3ZkFTdVpZcVJXWE1HdzJ4QkI0UFlCS0RZN1NYajVCaUp4Q25IOU5KZGVERFZ4ZGVaRXVEWXZxSkFFY1RXRHhrVm5mYlRENEpDc3l1SEhBQjJwZmJrendUYTJmYjZFRmQ2TDJnd0ZHQnFiWFVLc3pqSEJNWGlWZHZYTXk2RXVLQTczOW5Xclg2WVpMdVdTUWlFMnhLQkRLd0NHeld4ZGJZTlZBdVg4QjRGVXVWZ2drYTdGZnQ2dCJ9
  seed-3-libp2p.peerid: MTJEM0tvb1c5dGZROGV6NG1Sb2czQkNjU240Snc3dlBWQ0hlNHF5ZUhOM2oxY0xWRHdVUgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-3
---
apiVersion: v1
data:
  key-password: VlRKTjdxQ3RGcnFocjR2cVBjdmgzNDRNeGNNUkxLRjlWZFRkelAzWDRra0pXcXFiSHJiVlgzZlRtM003NHYzUA==
  libp2p-password: NEZ2eFZWYnB2TXNybjkzeHJ2aDRkdmdqdjdrdm1QcktiY2s0SzlmZEprcFdKbmZoUHdKZkxzd0htdnRGZG5IZw==
  seed-4-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjZqREpIS3dveUJGcU1KUTZTMkp2anR3SmhYalJFTTdpZWZ0c3ZaMSIsInB3c2FsdCI6IkJkekRBeFpSbVpQYTFLdlRuOFpZV3YyS0NXWkMiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJEUTRtQUM5Rzd1WWh1MWtneWpqUW5IcndQOUg1WjN4SjM4Q0FWYzZZenZOSEVQYzVybm9hSm8xMjNtd3Y5ejZSTE1WcVk2NFl6In0=
  seed-4-key.pub: QjYycWpXVzNjTVppM3ZNQW5lZTVZeHVFQTNvcTM4bkJoaW5MUnMyMzFQWTcxSjZHeHFlVDRYVQo=
  seed-4-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhBZFlNd2ExTVI4dkhGamZTbVJDODVWb0NNc0g2VkY0OHpkWFVlYyIsInB3c2FsdCI6IkE2YlNtVHRUWEZNNEJXSFF3UHltZUxDOFZzV0wiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI2cGZTRWpyMlJ2MXVaYVFaTnA5Z0xZVjFYRXNIVFNQM3Fmc3dmUEtoamNlNkZQWnI0aFR2b3ZpbzRMZVZib0FNN25DUk54SmVTYTVxeEoxQWRSaU5GNnU1a3JVTVVYTlFUMzVEVXBaQXgxRXY3amZ0UXRpWDNGemtzY1pUU0xUdkx3OGZNVjYzY1dWUFFaOFRaTUVBVVhENHlHUlc0M3NpdHduNjJmQ0pXMmU0SFBKTlkzNHJCQ2h3MzFnSmUxREcxUFhuVER5ano0RUtpekN6TkpXcUhLNUV0dlFtSjV4VERSZFJ6QWdvOUU5OXR4b0M3UzRpdlhNOGJQRFpxNmQxUDcxZG9aUnlTTWdrQU55b0tkd3VXSFd6VDRVQ2llaTlBanZwNCJ9
  seed-4-libp2p.peerid: MTJEM0tvb1dSa1l2OHVXRTlxTURRTUpRTUFmdGZFUnA1S0Juc012RTZ1a1NHMWs4UlNmcAo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-4
---
apiVersion: v1
data:
  key-password: a3drOXBoYno5TFBGRkNmdndneEtSbXpNM3pwTHhIUkpocVdWTGhSVEhuejNOWEZrNGR6ZHBUZ21WaEpwWFJYYg==
  libp2p-password: NHJUN3JQWFhwSjRMbWZwY1dmNE1xRjNDYmszRkhYZmN4V0xXd056SnBWa0M3ZEtKRndiaG10a3RDZzR3M3NrdA==
  seed-5-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhNV0MxS2FGV2lVUzJHb28ycnpic2NDRkpHNm5ScVdaV1IyeVhzOSIsInB3c2FsdCI6IjhRQlpBdXRocVFwSlBZM1dNNTk3dVZybUh0SG8iLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJFTWhUbVpSbW9HdjNCSExHSzUxdEJKWHN3SzRpclJoN2JTZlNHRHFwM1hFaFZWTHFlZ1JGTDE3TUJLZ0xlVjZiaHRodDJWbk5FIn0=
  seed-5-key.pub: QjYycWl6UVBnbWdSek1HYk11VXNlZ3RtU3BWYnN5b0xpQjRkMzJCVVZYQTI4cWQ0TjNDN0sxZQo=
  seed-5-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjdEZG5YS0hob1I1OVNhVVM4allNQTQyZnlObkdFd3BLOXR2WXZOZSIsInB3c2FsdCI6IkJBRUFiTnhWclJTeGt3aEVQZVJOUnp2TEs0Z3ciLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI5Mno5V2VSYVpONjYzR3RyNUttNWl3enN1RHNSZVZSMURrZVk1bWtVRWM1UTFDcVNvMTJwelNVTEF5VmJLc01ORmNHQVJNajZLWFFTUGpUY2ZrdXNCcDc0aWhobWZZcmQxb1dRUFl0R2RrV29pNTh2V3JHc1pXb2E4eThCanZqcWk3b0drUGtMQlVGSkNpY2VCbksxQ2JWWm5hTjRzeVQzTHBnRnRFa29DR0ZzVXFraUpZS2lQWmZMTXZRR280ejlhVzRqUkx6RkpER0tWWjRyM2d1ZEh5OFg2dWViMXhRejZ6ZDZBNHlnQ0Y0MmphZXpyN0RoS29na0FKeVRyR1VKTFQyeUQ4NmlBeGJVZ2p5b3hRWm5WSzI4THlBSDdrd2tCd2JHTiJ9
  seed-5-libp2p.peerid: MTJEM0tvb1dLU2RpRjFWV2hKc1FxREdYMXdTMjhhWlRySkNLdE5EZGt2ZXNnQXNTVDdObwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-5
---
apiVersion: v1
data:
  key-password: VEhXa1g3eG4zems3a0t3Q1JKY21mVkNoalZ0alg0ajdqcHhjdHJIZktQTDRuQ2ZGbTQ0Z1RGWHI5NGRGZk5MNw==
  libp2p-password: cGJXcFh3N3hySmZxcTM0UGtrc1hzWHJta0t0d3pIV3RYM3Jja1Z2VndGdkpLcmo3RjdmaE5mckZzTHJxd21WMw==
  seed-6-key: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhSbmFycmVMZlRxMnd4OTN3SzQxdVozWks5Q0RTS250cjhZUjN5aSIsInB3c2FsdCI6IkE3ZnZSYnY2eWNNU1F6elBidXhVR1dWYUpyTlIiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiJDdkgyS0VWMUVxUTcxdEtLd3lFR0pRUkJkN1IxQnRHampUbXd2akt6aE5HU0hUd1ZuSjd2RVlpVDRHc3JNbUxSQTlYOVZZYkNlIn0=
  seed-6-key.pub: QjYycXJ2dGtxMVBYeWpLbnJZYjdOVGdaSFZGYmZkcEFibU40TFczV2lzeFdSNXFYc3U3Q0N3Zwo=
  seed-6-libp2p: eyJib3hfcHJpbWl0aXZlIjoieHNhbHNhMjBwb2x5MTMwNSIsInB3X3ByaW1pdGl2ZSI6ImFyZ29uMmkiLCJub25jZSI6IjhhRHdiTm5LeEZpNFFpZERBRW1WVWFudmFHQjluNTRyZ0RTTW5pVCIsInB3c2FsdCI6IjlydkNrNWFlV21TQlJnOENScDYzVWJoOFd0NFYiLCJwd2RpZmYiOlsxMzQyMTc3MjgsNl0sImNpcGhlcnRleHQiOiI2YlplTHRKSHNYNW5pTXpyOGNValIxSzh6M2JGeGpiRG9McmNaekQyUjZHNG8yenM3Y2ZhVE5Va1dvekxmNlVxcVdmeVBCQm9jR3RzMnlqM0hjeEt1djRDSHAxOFY4UnhLdkFud2lQMko4SGlIb1NxWngxYm1OWjNid2dvc1plRWlVNG1aeTg1RlJVYktramlWNG54TnlFMXJUOGk1VUpFZzN1NmlwZVFFNE1iTWFGb1NkUGRQdTFpVEVRTVMxNVBHZ2hzSnlwZzZuajk2TVpORTZIZ0dBYnVHNnh5MlVHRUpZNm9pVW11dXFkOWtLbnpUb2NQbnRDQkdEMXJ0YkdKdkVUWm8xU2M4RFFFZ0hTTmJIR1Nhc2hUQ1d3dERldExtc21pQiJ9
  seed-6-libp2p.peerid: MTJEM0tvb1dDYlBCUDRveFd6YnczS3BLTEVVR2JBSzZaaVFleDJWVlVmNTYySlI3TGY3Rwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: seed-6
---
