deployment:
  testnet: "mainnet"
  name: "helm-example"
  image: gcr.io/o1labs-192920/mina-daemon:1.3.1.2-25388a0-bullseye-mainnet
  runtimeConfig:
  customEntrypoint:
    enabled: false
    entrypoint: ""
  peerListURL: "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt"
  seedPeers:
    - /dns4/seed-1.mainnet.o1test.net/tcp/10000/p2p/12D3KooWCa1d7G3SkRxy846qTvdAFX69NnoYZ32orWVLqJcDVGHW
    - /dns4/seed-2.mainnet.o1test.net/tcp/10001/p2p/12D3KooWK4NfthViCTyLgVQa1WvqDC1NccVxGruCXCZUt3GqvFvn
    - /dns4/seed-3.mainnet.o1test.net/tcp/10002/p2p/12D3KooWNofeYVAJXA3WGg2qCDhs3GEe71kTmKpFQXRbZmCz1Vr7
    - /dns4/seed-4.mainnet.o1test.net/tcp/10003/p2p/12D3KooWEdBiTUQqxp3jeuWaZkwiSNcFxC6d6Tdq7u2Lf2ZD2Q6X
    - /dns4/seed-5.mainnet.o1test.net/tcp/10004/p2p/12D3KooWL1DJTigSwuKQRfQE3p7puFUqfbHjXbZJ9YBWtMNpr3GU
    - /dns4/seed-6.mainnet.o1test.net/tcp/10005/p2p/12D3KooWHGx4u32n42ub7dJNxAcAhwiA1WDq1Zsjn3k7RsS11pE8

nodes:
  - name: "seed-1"
    class: "seed"
    # role is the expected use of this node, for us just a helm example
    # to query for nodes with this role: `kubectl get pods -l role=helm-example`
    role: "helm-example"
    replicas: 1
    fullname: "seed-1"
    exposeGraphql: false
    # seedFlags is a boolean that simply controls a set of flags for seed nodes
    #  specifically --seed and --enable-peer-exchange true
    seedFlags: true
    logLevel: Info
    fileLogLevel: Error
    maxConnections: 75
    ports:
      client: "8301"
      graphql: "3085"
      metrics: "9100"
      p2p: "10000"
    # the archive section allows configuring an archive node to talk to in the same namespace
    # archive nodes are not supported by this chart, see helm/archive-node
    archive:
      enabled: false
      address: archive-1:3086
    # libp2pKeys configures the static libp2p networking keypair so that other nodes can
    #   consistently find this one on the network. Important for seeds but does not play nice
    #   yet with "replicas > 1"
    libp2pKeys:
      enabled: true
    # minaKeys configures a mina keypair, and weather to use it for producing blocks
    minaKeys:
      enabled: false
      produceBlocks: true
  - name: "block-producer-1"
    class: "block-producer"
    # role is the expected use of this node, for us just a helm example
    # to query for nodes with this role: `kubectl get pods -l role=helm-example`
    role: "helm-example"
    replicas: 3
    fullname: "block-producer-1"
    seedFlags: false
    logLevel: Debug
    fileLogLevel: Error
    maxConnections: 25
    ports:
      client: "8301"
      graphql: "3085"
      metrics: "9100"
      p2p: "10001"
    # the archive section allows configuring an archive node to talk to in the same namespace
    # archive nodes are not supported by this chart, see helm/archive-node
    archive:
      enabled: false
      address: archive-2:3086
    # libp2pKeys configures the static libp2p networking keypair so that other nodes can
    #   consistently find this one on the network. Important for seeds but does not play nice
    #   yet with "replicas > 1"
    libp2pKeys:
      enabled: false
    # minaKeys configures a mina keypair, and weather to use it for producing blocks
    minaKeys:
      enabled: true
      produceBlocks: true

requests:
  memory: "20.0Gi"
  cpu: "8"

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 5
  initialDelaySeconds: 30
