steps:
- commands:
  - "dhall-to-yaml --quoted <<< './buildkite/test-drive/dynamic/Test.dhall' | buildkite-agent pipeline upload"
  label: ":hammer: Starting forge"
  agents:
    size: "generic"
  plugins:
  - docker#v5.9.0:
      environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      image: "codaprotocol/ci-toolchain-base:v3"
      propagate-environment: true
      mount-buildkite-agent: true
