apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.leaderboard.name }}
spec:
  schedule: "{{ .Values.leaderboard.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: {{ .Values.volume.name }}
              secret:
                secretName: {{ .Values.volume.secretName }}
          containers:
            - name: {{ .Values.leaderboard.containerName }}
              image: {{ .Values.leaderboard.image }}
              imagePullPolicy: Always
              env:
                - name: PGCONN1
<<<<<<< HEAD
<<<<<<< HEAD
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB1 }}
                - name: PGCONN2
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB2 }}
=======
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB }}
                - name: PGCONN2
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB }}
>>>>>>> feat: Added second PGCONN env var to helm chart
=======
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB1 }}
                - name: PGCONN2
                  value: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresHost }}:{{ .Values.postgresql.postgresPort }}/{{ .Values.postgresql.postgresDB2 }}
>>>>>>> feat: Added helm chart values for second DB
              volumeMounts:
                - name: {{ .Values.volume.name }}
                  mountPath: {{ .Values.volume.mountPath }}
                  subPath: {{ .Values.volume.subPath }}
                  readOnly: true
