apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.workerName }}
  labels:
    app: {{$.Values.workerName}}
    billing: itn3-testnet
spec:
  replicas: {{ $.Values.workerReplicas }}
  selector:
    matchLabels:
      app: {{$.Values.workerName}}
  template:
    metadata:
      labels:
        app: {{$.Values.workerName}}
        testnet: {{ $.Values.testnetName }}
        role: snark-worker
        billing: itn3-testnet
        version: {{ trunc 6 (split ":" $.Values.mina.image)._1 | trimSuffix "-" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: worker
        resources:
          limits:
            memory: 16.0Gi
          requests:
            memory: {{$.Values.workerMemRequest}}
            cpu: {{$.Values.workerCpuRequest}}
        image: {{ $.Values.mina.image }}
        {{ if $.Values.mina.useCustomEntrypoint -}}
        command: [{{ $.Values.mina.customEntrypoint }}]
        {{- end }}
        args: [
          "internal", 
          "snark-worker", 
          "-proof-level","full",
          "-shutdown-on-disconnect", "false", "-daemon-address",
          "{{ $.Values.coordinatorHostName }}:{{ $.Values.coordinatorRpcPort }}"
        ]
        env:
          - name: "RAYON_NUM_THREADS"
            value: "4"
        imagePullPolicy: Always
{{- include "nodeSelector.preemptible" $.Values | indent 6 }}
