site_name: Coda Documentation
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - My First Transaction: my-first-transaction.md
  - Become a Node Operator: node-operator.md
  - Contributing to Coda: contributing.md
  - Advanced:
    - Coda Protocol Architecture:
      - Overview: architecture/index.md
      - Lifecycle of a Payment: architecture/lifecycle-payment.md
    - GraphQL API: graphql-api.md
  - CLI Reference: cli-reference.md
  - Glossary: glossary.md
markdown_extensions:
  - admonition