apiVersion: batch/v1
kind: CronJob
metadata:
  name: general-clean-ci-artifacts
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: artifact-cleaner
            image: gcr.io/o1labs-192920/gcloud-cleaner:0.0.1
            imagePullPolicy: IfNotPresent
            command: ["python3"]
            args: ["/code/main.sh"]
            env:
            - name: AGE
              value: 90
            - name: DRYRUN
              value: "true"
            - name: GCLOUD_KEYFILE
              value: /gcloud/keyfile.json
            volumeMounts:
            - mountPath: /gcloud/
              name: gcloud-keyfile
            volumes:
            - name: gcloud-keyfile
              secret:
                defaultMode: 256
                items:
                - key: keyfile
                  path: keyfile.json
                secretName: gcloud-keyfile
          restartPolicy: OnFailure

