on:
  pull_request:
    types: [labeled, synchronize]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Coda Pipeline
        uses: buildkite/trigger-pipeline-action@v1.2.0
        if: contains(github.event.pull_request.labels.*.name, 'ci-build-me')
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          PIPELINE: "o-1-labs-2/coda"
          COMMIT: ${{ github.sha }}
          BRANCH: ${{ github.event.pull_request.head }}
          MESSAGE: ":github: Triggered from a GitHub Action"
